name: block_touching_object_state

robot_state_dim: 9
world_state_dim: 3
action_dim: 2

env_runner: 
  _target_:  fail.env_runner.block_touching_object_state_runner.BlockTouchingObjectStateRunner
  num_train: 0
  num_train_vis: 0
  train_start_seed: 0
  num_test: 1
  num_test_vis: 1
  test_start_seed: 100000
  max_steps: 350
  num_obs_steps: ${num_obs_steps}
  num_action_steps: ${num_action_steps}
  fps: 5
  past_action: ${past_action_visible}
  abs_action: False
  num_envs: null

dataset:
  _target_: fail.dataset.object_state_dataset.ObjectStateDataset
  path: data/block_touching_100
  horizon: ${num_obs_steps}
  pad_before: ${eval:'${num_obs_steps}-1'}
  pad_after: ${eval:'${num_action_steps}-1'}
  seed: 0
  harmonic_action: False 
  val_ratio: 0.02
