name: peg_insertion

dataset:
  _target_: fail.dataset.harmonic_dataset.HarmonicDataset
  path: data/10_push_expert
  horizon: ${obs_horizon}
  pad_before: 0
  pad_after: 0
  seed: 0
  val_ratio: 0.02
