name: block_touching 

dataset:
  _target_: fail.dataset.harmonic_dataset.HarmonicDataset
  path: data/100_touch_expert
  horizon: ${obs_horizon}
  pad_before: 0
  pad_after: 0
  seed: 0
  val_ratio: 0.02
