name: peg_insertion

robot_state_dim: 9
object_state_dim: 3
action_dim: 3
z_dim: 256

encoder:
  _target_: fail.model.modules.RobotStateObjectPoseEncoder
  robot_state_dim: ${robot_state_dim}
  object_state_dim: ${object_state_dim}
  model_dim: 64
  trans_out_dim: 32
  trans_layers: 4
  trans_heads: 8
  z_dim: ${z_dim}
  seq_len: ${eval:'${obs_horizon}*${obs_key_points}'}
  dropout: 0.1

so2_encoder:
  _target_: fail.model.modules.SO2RobotStateObjectPoseEncoder
  robot_state_dim: ${robot_state_dim}
  object_state_dim: ${object_state_dim}
  model_dim: 64
  trans_out_dim: 32
  trans_layers: 4
  trans_heads: 8
  L: 3
  z_dim: ${z_dim}
  seq_len: ${eval:'${obs_horizon}*${obs_key_points}'}
  dropout: 0.1

dataset:
  _target_: fail.dataset.object_state_dataset.ObjectStateDataset
  path: data/100_expert
  horizon: ${obs_horizon}
  pad_before: 0
  pad_after: 0
  seed: 0
  val_ratio: 0.02
