name: peg_insertion_object_state

robot_state_dim: 9
object_state_dim: 3
action_dim: 3

env_runner: 
  _target_:  fail.env_runner.drake_object_state_runner.DrakeObjectStateRunner
  env:peg_insertion 
  num_train: 10
  num_train_vis: 2
  train_start_seed: 0
  num_test: 50
  num_test_vis: 10
  test_start_seed: 100000
  max_steps: 100
  num_obs_steps: ${num_obs_steps}
  num_action_steps: ${num_action_steps}
  fps: 5
  past_action: ${past_action_visible}
  abs_action: False
  num_envs: null


dataset:
  _target_: fail.dataset.object_state_dataset.ObjectStateDataset
  path: data/peg_insertion_100
  horizon: ${num_obs_steps}
  pad_before: 0
  pad_after: ${eval:'${num_action_steps}-1'}
  seed: 0
  val_ratio: 0.02
