defaults:
  - _self_
  - task: block_touching_object_state 

name: train_explicit_policy
_target_: fail.workflow.explicit_workflow.ExplicitWorkflow

robot_state_dim: ${task.robot_state_dim} 
world_state_dim: ${task.world_state_dim}
action_dim: ${task.action_dim} 
task_name:  ${task.name}
exp_name: 'default'
past_action_visible: False

num_action_steps: 1
num_obs_steps: 2
num_robot_state_step: 10
num_robot_state: ${eval:'${num_obs_steps}*${num_robot_state_step}'}
num_world_state: ${num_obs_steps}
z_dim: 512 
model_dim: 128
trans_out_dim: 128
trans_layers: 4
trans_heads: 8
lr: 1e-3
dropout: 0.1

policy:
  _target_: fail.policy.explicit_policy.ExplicitPolicy
  robot_state_dim: ${robot_state_dim}
  world_state_dim: ${world_state_dim}
  action_dim: ${action_dim}
  num_action_steps: ${num_action_steps}
  num_robot_state: ${num_robot_state}
  num_world_state: ${num_world_state}
  z_dim: ${z_dim}
  dropout: ${dropout}

encoder:
  _target_: fail.model.modules.RobotStateObjectPoseEncoder
  robot_state_dim: ${robot_state_dim}
  object_state_dim: ${world_state_dim}
  robot_state_len: ${num_robot_state}
  object_state_len: ${num_world_state}
  model_dim: ${model_dim}
  trans_out_dim: ${trans_out_dim}
  trans_layers: ${trans_layers}
  trans_heads: ${trans_heads}
  z_dim: ${z_dim}
  dropout: ${dropout}

dataloader:
  batch_size: 256
  num_workers: 1
  shuffle: True
  pin_memory: True
  persistent_workers: False

val_dataloader:
  batch_size: 256
  num_workers: 1
  shuffle: False
  pin_memory: True
  persistent_workers: False

optimizer:
  _target_: torch.optim.AdamW
  lr: ${lr}
  betas: [0.95, 0.999]
  eps: 1e-8
  weight_decay: 1e-6

training:
  device: 'cuda:0'
  seed: 0
  resume: True
  lr_warmup_steps: 500
  num_epochs: 500
  checkpoint_every: 100
  rollout_every: 100
  val_every: 1
  tqdm_interval_sec: 1.0

logging:
  project: ${task_name} 
  resume: True
  mode: online
  name: ${now:%Y.%m.%d-%H.%M.%S}_${name}_${task_name}
  tags: ["${name}", "${task_name}", "${exp_name}"]
  id: null
  group: null

checkpoint:
  topk:
    monitor_key: test_mean_score
    mode: max
    k: 5
    format_str: 'epoch={epoch:04d}-test_mean_score={test_mean_score:.3f}.ckpt'
  save_last_checkpoint: True
  save_last_snapshot: False

multi_run:
  run_dir: data/outputs/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}_${task_name}
  wandb_name_base: ${now:%Y.%m.%d-%H.%M.%S}_${name}_${task_name}

hydra:
  job:
    override_dirname: ${name}
  run:
    dir: data/outputs/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}_${task_name}
  sweep:
    dir: data/outputs/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}_${task_name}
    subdir: ${hydra.job.num}
